version: "3.8"

services:
  team_db:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - team_volume:/var/opt/mssql
    container_name: team_db
    environment:
      SA_PASSWORD: "Superl33tpassw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  team_api:
    build:
      context: .
      dockerfile: TeamAPI/TeamAPI/Dockerfile
    container_name: team_api
    depends_on:
      - team_db
    ports:
      - "8080:8080"
      - "8081:8081"

  pokem_api:
    build:
      context: .
      dockerfile: PokeAPI/PokeAPI/Dockerfile
    container_name: pokem_api
    ports:
      - "8082:8082"

volumes:
  team_volume:
